version: "3.4"

services:
    whichphone:
        image: whichphone
        container_name: whichphone
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 4008:3000
        networks:
            - nginx-proxy-manager_default
        volumes:
            - .:/app
        restart: unless-stopped
        labels:
            - "com.centurylinklabs.watchtower.enable=false"

volumes:
    data:

networks:
    nginx-proxy-manager_default:
        external: false
        name: nginx-proxy-manager_default
