version: "3.4"

services:
    whichphone:
        image: whichphone
        container_name: whichphone
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: production
        ports:
            - 4008:3000
        volumes:
            - .:/app
        restart: unless-stopped

volumes:
    data:

networks:
    default:
        external:
            name: nginx-proxy-manager_default
