const mongoose = require('mongoose');

const deviceSchema = new mongoose.Schema({
    DeviceName: String,
    Brand: String,
    pictureURL:String,
    technology: String,
    gprs: String,
    edge: String,
    announced: String,
    status: String,
    dimensions: String,
    weight: String,
    sim: String,
    type: String,
    size: String,
    resolution: String,
    display_c: String,
    card_slot: String,
    alert_types: String,
    loudspeaker_: String,
    sound_c: String,
    bluetooth: String,
    gps: String,
    radio: String,
    usb: String,
    messaging: String,
    browser: String,
    java: String,
    features_c:String,
    battery_c: String,
    talk_time: String,
    colors: String,
    sensors: String,
    cpu: String,
    internal: String,
    os: String,
    body_c: String,
    primary_: String,
    video: String,
    secondary: String,
    speed: String,
    network_c: String,
    chipset: String,
    features: String,
    music_play: String,
    protection: String,
    gpu: String,
    multitouch: String,
    loudspeaker: String,
    audio_quality: String,
    nfc: String,
    camera: String,
    display: String,
    performance: String,
    build: String,
    price: String,
    _2g_bands: String,
    _3_5mm_jack_: String,
    _3g_bands: String,
    _4g_bands:String
});

const deviceDB = mongoose.model('device', deviceSchema);

module.exports = deviceDB;
